require:
  - rubocop-performance
  - rubocop-rails
inherit_from: ./.rubocop_todo.yml

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Encoding:
  Enabled: true

Metrics/LineLength:
  Enabled: true
  Max: 180

AllCops:
  Exclude:
    - "db/**/*"
    - "lib/**/*"
    - "garbage/**/*"
