require: rubocop-performance
require: rubocop-rails
inherit_from: ./.rubocop_todo.yml

AlignParameters:
  EnforcedStyle: with_fixed_indentation

Encoding:
  Enabled: true

LineLength:
  Enabled: true
  Max: 120

AllCops:
  Exclude:
    - 'db/**/*'   
    - 'lib/**/*'   
    - 'garbage/**/*'  
 
