require:
  - rubocop-performance
  - rubocop-rails
inherit_from: ./.rubocop_todo.yml

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/Encoding:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

Layout/LineLength:
  Enabled: true
  Max: 180

AllCops:
  Exclude:
    - "db/**/*"
    - "lib/**/*"
    - "garbage/**/*"
