require:
  - rubocop-performance
  - rubocop-rails
inherit_from: ./.rubocop_todo.yml

AlignParameters:
  EnforcedStyle: with_fixed_indentation

Encoding:
  Enabled: true

LineLength:
  Enabled: true
  Max: 180

AllCops:
  Exclude:
    - "db/**/*"
    - "lib/**/*"
    - "garbage/**/*"
