# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: pds_db
  host: djet.cloudapp.net
#  username: root
#  password: ladder
  username: djet
  password: myhome1989

test:
  <<: *default
  database: djet_test

production:
  <<: *default
