find . -type f -name '*.haml' -exec sed -i -r 's/"IC"/"REF"/g' {} \;
find . -type f -name '*.haml' -exec sed -i -r 's/"Система"/"Сист."/g' {} \;
find . -type f -name '*.haml' -exec sed -i -r 's/"tag"/"TAG\/KKS"/g' {} \;
find . -type f -name '*.haml' -exec sed -i -r 's/"Desc"/"Описание"/g' {} \;
find . -type f -name '*.haml' -exec sed -i -r 's/"ShortDesc"/"Описание"/g' {} \;
find . -type f -name '*.haml' -exec sed -i -r 's/"Desc_RU"/"Описание"/g' {} \;
find . -type f -name '*.haml' -exec sed -i -r 's/"Desc_EN"/"Описание(EN)"/g' {} \;
find . -type f -name '*.haml' -exec sed -i -r 's/"connection"/"Соединение"/g' {} \;
find . -type f -name '*.haml' -exec sed -i -r 's/"room"/"Помещение"/g' {} \;
find . -type f -name '*.haml' -exec sed -i -r 's/"model"/"Компонент"/g' {} \;
find . -type f -name '*.haml' -exec sed -i -r 's/"Algorithm"/"Алгоритм"/g' {} \;
find . -type f -name '*.haml' -exec sed -i -r 's/"sd_N"/"Сим. диаграмма"/g' {} \;
find . -type f -name '*.haml' -exec sed -i -r 's/"tag_RU"/"TAG_RU"/g' {} \;
find . -type f -name '*.haml' -exec sed -i -r 's/"tag_EN"/"TAG\/KKS"/g' {} \;
find . -type f -name '*.haml' -exec sed -i -r 's/"ed_power"/"Сил. пит."/g' {} \;
find . -type f -name '*.haml' -exec sed -i -r 's/"anc_power"/"Пит. сигн."/g' {} \;
find . -type f -name '*.haml' -exec sed -i -r 's/"Тип В ИС"/"Тип в ИС"/g' {} \;
find . -type f -name '*.haml' -exec sed -i -r 's/"kks"/"TAG\/KKS"/g' {} \;
